spring:
  application:
    name: Flow-Tree
    secret-key: ${SECRET_KEY}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URI}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

